name: broady_lite
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get:
  get_storage:
  cupertino_icons:
  image_picker: ^1.0.7
  path_provider:
  path: 
  sqflite:
  typed_data:
  http:
  photo_manager: ^3.0.0-dev.5
  photo_manager_image_provider:
  exif:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
