// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD80-ZKPyPq1l8bKFD8_xSPJuFnS_lF4Wo',
    appId: '1:48400422065:web:2b7cf6ad304c9a25863e90',
    messagingSenderId: '48400422065',
    projectId: 'sorialbum',
    authDomain: 'sorialbum.firebaseapp.com',
    storageBucket: 'sorialbum.appspot.com',
    measurementId: 'G-H211JQZXZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAfTduUeT0wYqqrEWXEStm4vP7NI0mJ7w',
    appId: '1:48400422065:android:a152023346a92e64863e90',
    messagingSenderId: '48400422065',
    projectId: 'sorialbum',
    storageBucket: 'sorialbum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-PBc85PEh26gl4qBOaJm4stk55a6zaJM',
    appId: '1:48400422065:ios:655cf79cc927c289863e90',
    messagingSenderId: '48400422065',
    projectId: 'sorialbum',
    storageBucket: 'sorialbum.appspot.com',
    iosBundleId: 'com.sigongan.broady-lite',
  );
}
